// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDczldLnBroT5jWi5zD53fVN2nSZwuBQdg',
    appId: '1:1048336202932:web:fbb548c97e70c91dc36be1',
    messagingSenderId: '1048336202932',
    projectId: 'tiktok-clone-44348',
    authDomain: 'tiktok-clone-44348.firebaseapp.com',
    storageBucket: 'tiktok-clone-44348.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlFtSf61Jp_w4XGGQ2XyIQFkRggGKdnl4',
    appId: '1:1048336202932:android:1efd333cc7c73111c36be1',
    messagingSenderId: '1048336202932',
    projectId: 'tiktok-clone-44348',
    storageBucket: 'tiktok-clone-44348.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARkn5UhZQSDDfPGBrkZc0zYRyOH2O1m0Y',
    appId: '1:1048336202932:ios:d40954a56762b515c36be1',
    messagingSenderId: '1048336202932',
    projectId: 'tiktok-clone-44348',
    storageBucket: 'tiktok-clone-44348.firebasestorage.app',
    iosBundleId: 'com.example.tiktok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARkn5UhZQSDDfPGBrkZc0zYRyOH2O1m0Y',
    appId: '1:1048336202932:ios:d40954a56762b515c36be1',
    messagingSenderId: '1048336202932',
    projectId: 'tiktok-clone-44348',
    storageBucket: 'tiktok-clone-44348.firebasestorage.app',
    iosBundleId: 'com.example.tiktok',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDczldLnBroT5jWi5zD53fVN2nSZwuBQdg',
    appId: '1:1048336202932:web:a1c6da9857f67480c36be1',
    messagingSenderId: '1048336202932',
    projectId: 'tiktok-clone-44348',
    authDomain: 'tiktok-clone-44348.firebaseapp.com',
    storageBucket: 'tiktok-clone-44348.firebasestorage.app',
  );
}
